package commcare.capstone.comcare.webservice;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 10/6/2017 10:03:52 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class LoginRequest implements KvmSerializable {

    public String password;
    public String interfaceVersion;
    public String login;
    public String requestDate;
    public boolean requestDateSpecified;
    public long token;
    public boolean tokenSpecified;
    
    public LoginRequest(){}
    
    public LoginRequest(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("password"))
        {
            Object obj = soapObject.getProperty("password");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                password = j.toString();
            }else if (obj!= null && obj instanceof String){
                password = (String) obj;
            }
        }
        if (soapObject.hasProperty("interfaceVersion"))
        {
            Object obj = soapObject.getProperty("interfaceVersion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                interfaceVersion = j.toString();
            }else if (obj!= null && obj instanceof String){
                interfaceVersion = (String) obj;
            }
        }
        if (soapObject.hasProperty("login"))
        {
            Object obj = soapObject.getProperty("login");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                login = j.toString();
            }else if (obj!= null && obj instanceof String){
                login = (String) obj;
            }
        }
        if (soapObject.hasProperty("requestDate"))
        {
            Object obj = soapObject.getProperty("requestDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                requestDate = j.toString();
            }else if (obj!= null && obj instanceof String){
                requestDate = (String) obj;
            }
        }
        if (soapObject.hasProperty("requestDateSpecified"))
        {
            Object obj = soapObject.getProperty("requestDateSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                requestDateSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                requestDateSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("token"))
        {
            Object obj = soapObject.getProperty("token");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                token = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                token = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("tokenSpecified"))
        {
            Object obj = soapObject.getProperty("tokenSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                tokenSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                tokenSpecified = (Boolean) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return password;
            case 1:
                return interfaceVersion;
            case 2:
                return login;
            case 3:
                return requestDate;
            case 4:
                return requestDateSpecified;
            case 5:
                return token;
            case 6:
                return tokenSpecified;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 7;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "password";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "interfaceVersion";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "login";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "requestDate";
                break;
            case 4:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "requestDateSpecified";
                break;
            case 5:
                info.type = Long.class;
                info.name = "token";
                break;
            case 6:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "tokenSpecified";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
